version: '3'

services:
  postgres:
    image: 'postgres:11.5'
    environment:
      - 'POSTGRES_USER=docker'
      - 'POSTGRES_DB=docker'
      - 'POSTGRES_PASSWORD=1234'
    expose:
      - '5432'
    ports:
      - '5432:5432'
